################################################
# PANTHEON ALASTRIA REGULAR NODE
################################################

FROM pegasyseng/pantheon:develop

# Start Pantheon with the config file
ENTRYPOINT ["/opt/pantheon/bin/pantheon"]
CMD ["--config-file=/root/alastria/config/config.toml"]
